In [1]:
import pandas as pd

In [3]:

temp_max_df = pd.read_csv('./sort_by_tempmax.csv')
temp_max_df.head()

,Unnamed: 0,datetime,name,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,513,2014,Beijing,42.0,19.8,30.4,39.0,19.8,29.3,10.1,...,29.2,10,NaN,2014-05-29T04:49:42,2014-05-29T19:34:19,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"ZBAA,54511099999"
1,3838,2023,Beijing,42.0,19.0,31.6,40.6,19.0,30.9,54.9,...,27.0,10,10.0,2023-07-06T04:52:02,2023-07-06T19:46:05,0.59,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"ZBAA,54511099999"
2,3824,2023,Beijing,41.0,20.0,32.3,39.2,20.0,31.3,53.4,...,30.1,10,10.0,2023-06-22T04:46:15,2023-06-22T19:46:31,0.13,Clear,Clear conditions throughout the day.,clear-day,"ZBAA,54511099999"
3,3833,2023,Beijing,41.0,24.0,33.0,40.1,24.0,32.7,58.6,...,26.2,9,10.0,2023-07-01T04:49:24,2023-07-01T19:46:58,0.42,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"ZBAA,54511099999"
4,2005,2018,Beijing,40.2,20.0,30.0,38.5,20.0,29.1,12.5,...,27.6,9,NaN,2018-06-29T04:48:33,2018-06-29T19:47:01,0.53,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,precipitation,"ZBAA,54511099999"